# Generated by Django 4.2.6 on 2023-11-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireemblemunit',
            name='genealogy',
        ),
    ]
