# Generated by Django 4.2.6 on 2023-11-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0002_remove_fireemblemunit_genealogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireemblemunit',
            name='father_name',
            field=models.CharField(blank=True, choices=[('Arden', 'Arden'), ('Azel', 'Azel'), ('Alec', 'Alec'), ('Claude', 'Claude'), ('Jamka', 'Jamka'), ('Dew', 'Dew'), ('Noish', 'Noish'), ('Fin', 'Fin'), ('Beowolf', 'Beowolf'), ('Holyn', 'Holyn'), ('Midayle', 'Midayle'), ('Levin', 'Levin'), ('Lex', 'Lex')], max_length=50, verbose_name='Father Name'),
        ),
    ]
