# Generated by Django 4.2.6 on 2023-11-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0003_alter_fireemblemunit_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireemblemgame',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='fireemblemgame',
            name='game_num',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fireemblemunit',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='fireemblemunit',
            name='father_name',
            field=models.CharField(blank=True, choices=[('Arden', 'Arden'), ('Azel', 'Azel'), ('Alec', 'Alec'), ('Claude', 'Claude'), ('Jamka', 'Jamka'), ('Dew', 'Dew'), ('Noish', 'Noish'), ('Fin', 'Fin'), ('Beowolf', 'Beowolf'), ('Holyn', 'Holyn'), ('Midayle', 'Midayle'), ('Levin', 'Levin'), ('Lex', 'Lex')], max_length=50, verbose_name='Father'),
        ),
    ]
