# Generated by Django 4.2.7 on 2023-12-03 16:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0004_alter_fireemblemgame_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireEmblemGenealogy',
            fields=[
                ('game_num', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('can_inherit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LyndisLeague',
            fields=[
                ('game_num', models.PositiveSmallIntegerField()),
                ('unit_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('will_inherit', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fireemblemunit',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='fireemblemunit',
            name='father_name',
        ),
        migrations.AlterField(
            model_name='fireemblemgame',
            name='game_num',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UnitSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stat_compare.fireemblemgame')),
                ('unit_name', smart_selects.db_fields.ChainedForeignKey(chained_field='game_num', chained_model_field='game_num', on_delete=django.db.models.deletion.CASCADE, sort=False, to='stat_compare.fireemblemunit')),
            ],
        ),
    ]
