# Generated by Django 4.2.7 on 2023-12-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0005_fireemblemgenealogy_lyndisleague_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fireemblemgame',
            old_name='display_name',
            new_name='display_gamename',
        ),
        migrations.RenameField(
            model_name='fireemblemgenealogy',
            old_name='display_name',
            new_name='display_unitname',
        ),
        migrations.RenameField(
            model_name='fireemblemunit',
            old_name='display_name',
            new_name='display_unitname',
        ),
    ]
