# Generated by Django 4.2.7 on 2023-12-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0010_delete_fireemblemgenealogy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenealogyDads',
            new_name='GenealogyDad',
        ),
        migrations.RenameModel(
            old_name='GenealogyKids',
            new_name='GenealogyKid',
        ),
        migrations.AlterField(
            model_name='userregistry',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
