# Generated by Django 4.2.7 on 2023-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0011_rename_genealogydads_genealogydad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyndisleague',
            name='will_inherit',
            field=models.BooleanField(choices=[(False, 'Main'), (True, 'Tutorial')], default=False, verbose_name='Campaign'),
        ),
    ]
