# Generated by Django 4.2.6 on 2023-11-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireEmblemGame',
            fields=[
                ('game_num', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Game ID')),
                ('game_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True, verbose_name='Game Title')),
            ],
        ),
        migrations.CreateModel(
            name='FireEmblemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50, verbose_name='Unit Name')),
                ('campaign', models.CharField(blank=True, choices=[('lyn_mode', 'Lyn Mode'), ('main', 'Main')], max_length=50, verbose_name='Campaign')),
                ('genealogy', models.CharField(blank=True, choices=[('father', 'Father'), ('child', 'Child')], max_length=50)),
                ('father_name', models.CharField(blank=True, choices=[('Arden', 'Arden'), ('Azel', 'Azel'), ('Alec', 'Alec'), ('Claude', 'Claude'), ('Jamka', 'Jamka'), ('Dew', 'Dew'), ('Noish', 'Noish'), ('Fin', 'Fin'), ('Beowolf', 'Beowolf'), ('Holyn', 'Holyn'), ('Midayle', 'Midayle'), ('Levin', 'Levin'), ('Lex', 'Lex')], max_length=50)),
                ('game_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stat_compare.fireemblemgame')),
            ],
        ),
    ]
