# Generated by Django 4.2.7 on 2023-12-03 23:49

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0007_rename_display_name_lyndisleague_display_unitname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='fireemblemunit',
            name='display_unitname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unitselect',
            name='game_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stat_compare.fireemblemgame', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='unitselect',
            name='unit_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='game_num', chained_model_field='game_num', on_delete=django.db.models.deletion.CASCADE, sort=False, to='stat_compare.fireemblemunit', verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='DragonsGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_list', models.JSONField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stat_compare.userregistry')),
            ],
        ),
    ]
