# Generated by Django 4.2.7 on 2023-12-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0008_userregistry_alter_fireemblemunit_display_unitname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenealogyDads',
            fields=[
                ('unit_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_unitname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenealogyKids',
            fields=[
                ('unit_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_unitname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dragonsgate',
            name='morph_list',
        ),
        migrations.RemoveField(
            model_name='lyndisleague',
            name='game_num',
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='bases',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='comparison_labels',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='current_cls',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='current_clstype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='current_lv',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='game_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='growths',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='promo_cls',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dragonsgate',
            name='unit_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
