# Generated by Django 4.2.7 on 2023-12-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0009_genealogydads_genealogykids_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FireEmblemGenealogy',
        ),
    ]
