# Generated by Django 4.2.7 on 2023-12-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_compare', '0012_lyndisleague_will_inherit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genealogydad',
            old_name='unit_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='lyndisleague',
            old_name='will_inherit',
            new_name='lyn_mode',
        ),
    ]
